FROM node:22.11-alpine AS build
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .
ARG NODE_ENV=production
ARG BACKEND_URL
ARG STREAMING_URL
RUN yarn build

FROM nginx:stable-alpine
EXPOSE 80
ENV PORT=80
ENV FALLBACK_PORT=4444
ENV CSP=
COPY installation/docker.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html