FROM node:22.11-alpine AS build
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .
ARG NODE_ENV=production
ARG BACKEND_URL=https://apollo-backend-dev-67f2c629cfb2.herokuapp.com
RUN yarn build

FROM nginx:stable-alpine
EXPOSE 5000
ENV PORT=5000
ENV FALLBACK_PORT=4444
ENV BACKEND_URL=https://apollo-backend-dev-67f2c629cfb2.herokuapp.com
ENV CSP=
COPY installation/docker.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html