FROM node:22.11-alpine

RUN apk update && \
    apk add inotify-tools && \
    rm -rf /var/cache/apk/*

WORKDIR /app
ENV NODE_ENV=development
ENV BACKEND_URL=http://host.docker.internal:8080

# Copy package files
COPY package*.json ./
COPY yarn.lock ./

# Install dependencies
RUN yarn install

# Copy source code
COPY . .

# Expose Vite port
EXPOSE 5173

# Start development server
CMD ["yarn", "dev"]