FROM node:22.11-alpine
RUN apk update && \
    apk add inotify-tools && \
    rm -rf /var/cache/apk/*
WORKDIR /app

ENV NODE_ENV=development
ENV BACKEND_URL=http://host.docker.internal:8080
ENV STREAMING_URL=ws://host.docker.internal:8080
ENV SENTRY_DSN=""
ENV IMGIX_DOMAIN=apollo-414916088.imgix.net

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install
COPY . .
EXPOSE 5173
CMD ["yarn", "dev"]