import { lazy } from 'react';

export const DatePicker = lazy(() => import('./DatePicker'));
export const ModalContainer = lazy(() => import('../containers/ModalContainer'));
export const OnboardingWizard = lazy(() => import('./OnboardingWizard'));
export const Login = lazy(() => import('./Login'));
export const Signup = lazy(() => import('./Signup'));
export const TrendsPanel = lazy(() => import('./TrendsPanel'));
export const WhoToFollowPanel = lazy(() => import('./WhoToFollowPanel'));
export const SignUpPanel = lazy(() => import('./SignUpPanel'));
export const CtaBanner = lazy(() => import('./CtaBanner'));
// export const PromoPanel = lazy(() => import('./PromoPanel')); TODO: Implement
export const HomeTimeline = lazy(() => import('./HomeTimeline'));
export const EmailConfirmation = lazy(() => import('./EmailConfirmation'));
// export const ChatWidget = lazy(() => import('./ChatWidget'));
export const SidebarMenu = lazy(() => import('./SidebarMenu'));
export const ProfileHoverCard = lazy(() => import('./ProfileHoverCard'));
export const StatusHoverCard = lazy(() => import('./StatusHoverCard'));
export const Logout = lazy(() => import('./Logout'));
export const PasswordReset = lazy(() => import('./PasswordReset'));
export const PasswordResetConfirm = lazy(() => import('./PasswordResetConfirm'));
export const SignupInvite = lazy(() => import('./SignupInvite'));
export const LandingTimeline = lazy(() => import('./LandingTimeline'));
export const ComposeEditor = lazy(() => import('./compose/editor'));
export const MediaGallery = lazy(() => import('./MediaGallery'));
export const Video = lazy(() => import('./Video'));
export const Audio = lazy(() => import('./Audio'));
export const AccountModerationModal = lazy(() => import('./modals/AccountModerationModal'));
export const ActionsModal = lazy(() => import ('./modals/ActionsModal'));
export const BoostModal = lazy(() => import ('./modals/BoostModal'));
export const ComposeModal = lazy(() => import ('./modals/ComposeModal'));
export const ConfirmationModal = lazy(() => import ('./modals/ConfirmationModal'));
export const HotkeysModal = lazy(() => import ('./modals/HotkeysModal'));
export const LikesModal = lazy(() => import ('./modals/LikesModal'));
export const MediaModal = lazy(() => import ('./modals/MediaModal'));
export const MentionsModal = lazy(() => import ('./modals/MentionsModal'));
export const MissingDescriptionModal = lazy(() => import ('./modals/MissingDescriptionModal'));
export const MuteModal = lazy(() => import ('./modals/MuteModal'));
export const ReplyMentionsModal = lazy(() => import ('./modals/ReplyMentionsModal'));
export const ReportModal = lazy(() => import ('./modals/ReportModal'));
export const RepostsModal = lazy(() => import ('./modals/RepostsModal'));
export const UnauthorizedModal = lazy(() => import ('./modals/UnauthorizedModal'));
export const UserPanel = lazy(() => import ('./UserPanel'));
export const EmojiPicker = lazy(() => import ('./emoji/components/EmojiPicker'));