import { lazy } from 'react';

export const DatePicker = lazy(() => import('./DatePicker'));
export const ModalContainer = lazy(() => import('./ModalContainer'));
export const OnboardingWizard = lazy(() => import('./OnboardingWizard'));
export const Login = lazy(() => import('./Login'));
export const Signup = lazy(() => import('./Signup'));
export const TrendsPanel = lazy(() => import('./TrendsPanel'));
export const WhoToFollowPanel = lazy(() => import('./WhoToFollowPanel'));
export const SignUpPanel = lazy(() => import('./SignUpPanel'));
export const CtaBanner = lazy(() => import('./CtaBanner'));
export const PromoPanel = lazy(() => import('./PromoPanel'));
export const AnnouncementsPanel = lazy(() => import('./AnnouncementsPanel'));
export const HomeTimeline = lazy(() => import('./HomeTimeline'));
export const EmailConfirmation = lazy(() => import('./EmailConfirmation'));
// export const ChatWidget = lazy(() => import('./ChatWidget'));
export const SidebarMenu = lazy(() => import('./SidebarMenu'));
export const ProfileHoverCard = lazy(() => import('./ProfileHoverCard'));
export const StatusHoverCard = lazy(() => import('./StatusHoverCard'));
export const Logout = lazy(() => import('./Logout'));
export const PasswordReset = lazy(() => import('./PasswordReset'));
export const PasswordResetConfirm = lazy(() => import('./PasswordResetConfirm'));
export const SignupInvite = lazy(() => import('./SignupInvite'));
export const LandingTimeline = lazy(() => import('./LandingTimeline'));
export const ComposeEditor = lazy(() => import('./compose/editor'));
export const MediaGallery = lazy(() => import('./MediaGallery'));
export const Video = lazy(() => import('./Video'));
export const Audio = lazy(() => import('./Audio'));