export interface SpaceConfig {
  name: string;
  path: string;
}

const spacesConfig: SpaceConfig[] = [
  { name: "League of Legends", path: "lol" },
  { name: "Elden Ring", path: "eldenring" },
  { name: "Valorant", path: "valorant" },
  { name: "Dota 2", path: "dota2" },
  { name: "Counter Strike", path: "cs" },
  { name: "Overwatch", path: "overwatch" },
  { name: "Rocket League", path: "rocketleague" },
  { name: "Fortnite", path: "fortnite" },
  { name: "Team Fortress 2", path: "tf2" },
  { name: "Street Fighter", path: "streetfighter" },
  { name: "Dark Souls 1", path: "darksouls1" },
  { name: "Dark Souls 2", path: "darksouls2" },
  { name: "Dark Souls 3", path: "darksouls3" },
  { name: "Bloodborne", path: "bloodborne" },
  { name: "Sekiro", path: "sekiro" },
  { name: "Demon's Souls", path: "demonssouls" },
  { name: "PUBG", path: "pubg" },
  { name: "Guilty Gear", path: "guiltygear" },
  { name: "Tekken", path: "tekken" },
  { name: "Smash Bros", path: "smashbros" },
  { name: "Mario", path: "mario" },
  { name: "Breath of the Wild", path: "botw" },
  { name: "Tears of the Kingdom", path: "totk" },
  { name: "World of Warcraft", path: "wow" },
  { name: "Hearthstone", path: "hearthstone" },
  { name: "Skyrim", path: "skyrim" },
  { name: "Destiny 2", path: "destiny2" },
  { name: "Titanfall", path: "titanfall" },
  { name: "Pokemon", path: "pokemon" },
  { name: "Diablo 1-4", path: "diablo" },
  { name: "Civilization Series", path: "civilization" },
  { name: "Path of Exile", path: "poe" },
  { name: "Hearts of Iron IV", path: "hoi4" },
  { name: "Smite", path: "smite" },
  { name: "Heroes of the Storm", path: "hots" },
  { name: "Elite Dangerous", path: "elitedangerous" },
  { name: "Final Fantasy", path: "finalfantasy" },
  { name: "Runescape", path: "runescape" },
  { name: "No Man's Sky", path: "nomanssky" },
  { name: "Undertale", path: "undertale" },
  { name: "Terraria", path: "terraria" },
  { name: "Minecraft", path: "minecraft" },
  { name: "Cuphead", path: "cuphead" },
  { name: "Fallout", path: "fallout" },
  { name: "Call of Duty", path: "cod" },
  { name: "Warzone", path: "warzone" },
  { name: "Monster Hunter", path: "monsterhunter" },
  { name: "FIFA", path: "fifa" },
  { name: "Madden", path: "madden" },
  { name: "2K", path: "2k" },
  { name: "NHL24", path: "nhl24" },
  { name: "DayZ", path: "dayz" },
  { name: "Clash of Clans", path: "clashofclans" },
  { name: "Rust", path: "rust" },
  { name: "Kingdom Hearts", path: "kingdomhearts" },
  { name: "Warframe", path: "warframe" },
  { name: "Guild Wars", path: "guildwars" },
  { name: "Star Citizen", path: "starcitizen" },
  { name: "Halo", path: "halo" },
  { name: "The First Descendent", path: "firstdescendent" },
  { name: "Stellar Blade", path: "stellarblade" },
  { name: "FNAF", path: "fnaf" },
  { name: "Cities Skylines", path: "citiesskylines" },
  { name: "Mount and Blade", path: "mountandblade" },
  { name: "Battlefront", path: "battlefront" },
  { name: "Battlefield", path: "battlefield" },
  { name: "Arma", path: "arma" },
  { name: "Dragon Age", path: "dragonage" },
  { name: "DragonFable", path: "dragonfable" },
  { name: "Assassin's Creed", path: "ac" },
  { name: "Ghost of Tsushima", path: "ghostoftsushima" },
  { name: "Red Dead Redemption", path: "rdr" },
  { name: "Grand Theft Auto", path: "gta" },
  { name: "Saint's Row", path: "saintsrow" },
  { name: "Dishonored", path: "dishonored" },
  { name: "Guitar Hero", path: "guitarhero" },
  { name: "Rock Band", path: "rockband" },
  { name: "Borderlands", path: "borderlands" },
  { name: "The Witcher III", path: "witcher3" },
  { name: "MLB The Show", path: "mlbtheshow" },
  { name: "Animal Crossing", path: "animalcrossing" },
  { name: "Deus Ex", path: "deusex" },
  { name: "Cyberpunk 2077", path: "cyberpunk2077" },
  { name: "Mortal Kombat", path: "mortalkombat" },
  { name: "Baldur's Gate 3", path: "bg3" },
];

export default spacesConfig;
